name: Research — Supplier/Vendor
description: Find suppliers and terms for materials/equipment
title: "Research: [supplier] for [service]"
labels: ["task","vendor"]
body:
  - type: input
    id: supplier
    attributes:
      label: Supplier
  - type: input
    id: service
    attributes:
      label: Service (cleanup / fencing / erosion)
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Pricing, delivery, credit terms, lead times
